// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {MxObject} parameter
 * @returns {MxObject[]}
 */
function JS_GetNodeParentChildren(parameter) {
	// BEGIN USER CODE
	
	return new Promise((resolve, reject) => {
		if (!parameter) {
			reject("No object!");
		}
		mx.data.get({
			xpath: '//' + parameter.getEntity() + '[TreeData.Parent = \'' + parameter.getGuid() + '\']',
			callback: resolve,
			error: reject
		});
	});
	// END USER CODE
}