// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treedata.proxies;

public class Set
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject setMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeData.Set";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		SetType("SetType"),
		_ChildCount("_ChildCount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Set(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeData.Set"));
	}

	protected Set(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject setMendixObject)
	{
		if (setMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TreeData.Set", setMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeData.Set");

		this.setMendixObject = setMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Set.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static treedata.proxies.Set initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treedata.proxies.Set.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static treedata.proxies.Set initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treedata.proxies.Set(context, mendixObject);
	}

	public static treedata.proxies.Set load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treedata.proxies.Set.initialize(context, mendixObject);
	}

	public static java.util.List<treedata.proxies.Set> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<treedata.proxies.Set> result = new java.util.ArrayList<treedata.proxies.Set>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TreeData.Set" + xpathConstraint))
			result.add(treedata.proxies.Set.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * Set value of SetType
	 * @param settype
	 */
	public final treedata.proxies.TreeDataSet getSetType()
	{
		return getSetType(getContext());
	}

	/**
	 * @param context
	 * @return value of SetType
	 */
	public final treedata.proxies.TreeDataSet getSetType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SetType.toString());
		if (obj == null)
			return null;

		return treedata.proxies.TreeDataSet.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SetType
	 * @param settype
	 */
	public final void setSetType(treedata.proxies.TreeDataSet settype)
	{
		setSetType(getContext(), settype);
	}

	/**
	 * Set value of SetType
	 * @param context
	 * @param settype
	 */
	public final void setSetType(com.mendix.systemwideinterfaces.core.IContext context, treedata.proxies.TreeDataSet settype)
	{
		if (settype != null)
			getMendixObject().setValue(context, MemberNames.SetType.toString(), settype.toString());
		else
			getMendixObject().setValue(context, MemberNames.SetType.toString(), null);
	}

	/**
	 * @return value of _ChildCount
	 */
	public final java.lang.Integer get_ChildCount()
	{
		return get_ChildCount(getContext());
	}

	/**
	 * @param context
	 * @return value of _ChildCount
	 */
	public final java.lang.Integer get_ChildCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._ChildCount.toString());
	}

	/**
	 * Set value of _ChildCount
	 * @param _childcount
	 */
	public final void set_ChildCount(java.lang.Integer _childcount)
	{
		set_ChildCount(getContext(), _childcount);
	}

	/**
	 * Set value of _ChildCount
	 * @param context
	 * @param _childcount
	 */
	public final void set_ChildCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _childcount)
	{
		getMendixObject().setValue(context, MemberNames._ChildCount.toString(), _childcount);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return setMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treedata.proxies.Set that = (treedata.proxies.Set) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeData.Set";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
