// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treedata.proxies;

public class TreeNode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject treeNodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeData.TreeNode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		_Root("_Root"),
		_HasChildren("_HasChildren"),
		Icon("Icon"),
		ClassName("ClassName"),
		Children("TreeData.Children"),
		Parent("TreeData.Parent"),
		TreeNode_Set("TreeData.TreeNode_Set");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TreeNode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TreeData.TreeNode"));
	}

	protected TreeNode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject treeNodeMendixObject)
	{
		if (treeNodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TreeData.TreeNode", treeNodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TreeData.TreeNode");

		this.treeNodeMendixObject = treeNodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TreeNode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static treedata.proxies.TreeNode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return treedata.proxies.TreeNode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static treedata.proxies.TreeNode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treedata.proxies.TreeNode(context, mendixObject);
	}

	public static treedata.proxies.TreeNode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treedata.proxies.TreeNode.initialize(context, mendixObject);
	}

	public static java.util.List<treedata.proxies.TreeNode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<treedata.proxies.TreeNode> result = new java.util.ArrayList<treedata.proxies.TreeNode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//TreeData.TreeNode" + xpathConstraint))
			result.add(treedata.proxies.TreeNode.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of _Root
	 */
	public final java.lang.Boolean get_Root()
	{
		return get_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of _Root
	 */
	public final java.lang.Boolean get_Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Root.toString());
	}

	/**
	 * Set value of _Root
	 * @param _root
	 */
	public final void set_Root(java.lang.Boolean _root)
	{
		set_Root(getContext(), _root);
	}

	/**
	 * Set value of _Root
	 * @param context
	 * @param _root
	 */
	public final void set_Root(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _root)
	{
		getMendixObject().setValue(context, MemberNames._Root.toString(), _root);
	}

	/**
	 * @return value of _HasChildren
	 */
	public final java.lang.Boolean get_HasChildren()
	{
		return get_HasChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of _HasChildren
	 */
	public final java.lang.Boolean get_HasChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._HasChildren.toString());
	}

	/**
	 * Set value of _HasChildren
	 * @param _haschildren
	 */
	public final void set_HasChildren(java.lang.Boolean _haschildren)
	{
		set_HasChildren(getContext(), _haschildren);
	}

	/**
	 * Set value of _HasChildren
	 * @param context
	 * @param _haschildren
	 */
	public final void set_HasChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _haschildren)
	{
		getMendixObject().setValue(context, MemberNames._HasChildren.toString(), _haschildren);
	}

	/**
	 * @return value of Icon
	 */
	public final java.lang.String getIcon()
	{
		return getIcon(getContext());
	}

	/**
	 * @param context
	 * @return value of Icon
	 */
	public final java.lang.String getIcon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Icon.toString());
	}

	/**
	 * Set value of Icon
	 * @param icon
	 */
	public final void setIcon(java.lang.String icon)
	{
		setIcon(getContext(), icon);
	}

	/**
	 * Set value of Icon
	 * @param context
	 * @param icon
	 */
	public final void setIcon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String icon)
	{
		getMendixObject().setValue(context, MemberNames.Icon.toString(), icon);
	}

	/**
	 * @return value of ClassName
	 */
	public final java.lang.String getClassName()
	{
		return getClassName(getContext());
	}

	/**
	 * @param context
	 * @return value of ClassName
	 */
	public final java.lang.String getClassName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClassName.toString());
	}

	/**
	 * Set value of ClassName
	 * @param classname
	 */
	public final void setClassName(java.lang.String classname)
	{
		setClassName(getContext(), classname);
	}

	/**
	 * Set value of ClassName
	 * @param context
	 * @param classname
	 */
	public final void setClassName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String classname)
	{
		getMendixObject().setValue(context, MemberNames.ClassName.toString(), classname);
	}

	/**
	 * @return value of Children
	 */
	public final java.util.List<treedata.proxies.TreeNode> getChildren() throws com.mendix.core.CoreException
	{
		return getChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of Children
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<treedata.proxies.TreeNode> getChildren(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<treedata.proxies.TreeNode> result = new java.util.ArrayList<treedata.proxies.TreeNode>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Children.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(treedata.proxies.TreeNode.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Children
	 * @param children
	 */
	public final void setChildren(java.util.List<treedata.proxies.TreeNode> children)
	{
		setChildren(getContext(), children);
	}

	/**
	 * Set value of Children
	 * @param context
	 * @param children
	 */
	public final void setChildren(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<treedata.proxies.TreeNode> children)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (treedata.proxies.TreeNode proxyObject : children)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Children.toString(), identifiers);
	}

	/**
	 * @return value of Parent
	 */
	public final treedata.proxies.TreeNode getParent() throws com.mendix.core.CoreException
	{
		return getParent(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent
	 */
	public final treedata.proxies.TreeNode getParent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treedata.proxies.TreeNode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent.toString());
		if (identifier != null)
			result = treedata.proxies.TreeNode.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Parent
	 * @param parent
	 */
	public final void setParent(treedata.proxies.TreeNode parent)
	{
		setParent(getContext(), parent);
	}

	/**
	 * Set value of Parent
	 * @param context
	 * @param parent
	 */
	public final void setParent(com.mendix.systemwideinterfaces.core.IContext context, treedata.proxies.TreeNode parent)
	{
		if (parent == null)
			getMendixObject().setValue(context, MemberNames.Parent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Parent.toString(), parent.getMendixObject().getId());
	}

	/**
	 * @return value of TreeNode_Set
	 */
	public final treedata.proxies.Set getTreeNode_Set() throws com.mendix.core.CoreException
	{
		return getTreeNode_Set(getContext());
	}

	/**
	 * @param context
	 * @return value of TreeNode_Set
	 */
	public final treedata.proxies.Set getTreeNode_Set(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treedata.proxies.Set result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TreeNode_Set.toString());
		if (identifier != null)
			result = treedata.proxies.Set.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TreeNode_Set
	 * @param treenode_set
	 */
	public final void setTreeNode_Set(treedata.proxies.Set treenode_set)
	{
		setTreeNode_Set(getContext(), treenode_set);
	}

	/**
	 * Set value of TreeNode_Set
	 * @param context
	 * @param treenode_set
	 */
	public final void setTreeNode_Set(com.mendix.systemwideinterfaces.core.IContext context, treedata.proxies.Set treenode_set)
	{
		if (treenode_set == null)
			getMendixObject().setValue(context, MemberNames.TreeNode_Set.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TreeNode_Set.toString(), treenode_set.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return treeNodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treedata.proxies.TreeNode that = (treedata.proxies.TreeNode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TreeData.TreeNode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
