// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treedata.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TreeData module

	public static java.lang.Long getNodesPerLevel()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TreeData.NodesPerLevel");
	}

	public static java.lang.Long getTreeDepth()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TreeData.TreeDepth");
	}
}